/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_PokerAI */

#ifndef _Included_controller_PokerAI
#define _Included_controller_PokerAI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_PokerAI
 * Method:    nextMove
 * Signature: (Lmodel/State;)Lmodel/Move;
 */
JNIEXPORT jobject JNICALL Java_controller_PokerAI_nextMove
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
