/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_PokerAI */

#ifndef _Included_controller_PokerAI
#define _Included_controller_PokerAI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_PokerAI
 * Method:    nativeNextMove
 * Signature: (ZD[DD[J[J)I
 */
JNIEXPORT jint JNICALL Java_controller_PokerAI_nativeNextMove
  (JNIEnv *, jclass, jboolean, jdouble, jdoubleArray, jdouble, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
