/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_State */

#ifndef _Included_model_State
#define _Included_model_State
#ifdef __cplusplus
extern "C" {
#endif
#undef model_State_INITIAL_STACK
#define model_State_INITIAL_STACK 1000.0
#undef model_State_SMALL_BLIND
#define model_State_SMALL_BLIND 5.0
#undef model_State_BIG_BLIND
#define model_State_BIG_BLIND 10.0
#undef model_State_INITIAL_MIN_RAISE
#define model_State_INITIAL_MIN_RAISE 10.0
/*
 * Class:     model_State
 * Method:    winningHand
 * Signature: ()Lmodel/Player;
 */
JNIEXPORT jobject JNICALL Java_model_State_winningHand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
