/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class tui_PokerAI */

#ifndef _Included_tui_PokerAI
#define _Included_tui_PokerAI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tui_PokerAI
 * Method:    nativeNextMove
 * Signature: (ZD[DD[J[J)I
 */
JNIEXPORT jint JNICALL Java_tui_PokerAI_nativeNextMove
  (JNIEnv *, jclass, jboolean, jdouble, jdoubleArray, jdouble, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
